# Generated by Django 2.1.7 on 2019-04-19 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['-value']},
        ),
    ]
